### ISSUE TITLE
Test Files Landing Blank Page

### ISSUE THREAD

**Issue by shobana-chandrasekar** [WowzaMediaSystems/wse-rest-library-php#23] opened 2017-08-10 12:06 UTC
I couldn't run and see the output of Test files. Is there any dependency files has to download ?

**Comment by IWriteThings** [comment] 2017-08-10 15:04
Can you provide more information about what you are trying to do or accomplish? Did you install using composer or follow the instructions found in issue #22? Examples of what you did, links to a repository, or gist, or something would be of great help for those of us working on trouble shooting any hiccups during this large change.

Thanks a bunch!

**Comment by nlmaca** [comment] 2017-08-14 21:42
I have the same problem. Didn't use composer install, because i cant find that in the readme file. I just uploaded the php code to my webserver, changed the constants.php (curl is installed), but getting a blanc page. 
apache error log: 
`[Mon Aug 14 23:38:23.913031 2017] [:error] [pid 11115] [client MY_IPADDRESS:62296] PHP Fatal error:  Uncaught Error: Class 'com\\wowza\\entities\\application\\StreamConfig' not found in /var/www/html/wowza_api/WSE/tests/application.php:10\nStack trace:\n#0 {main}\n  thrown in /var/www/html/wowza_api/WSE/tests/application.php on line 10`

install using composer? I don';t see that in the readme. How can i do that?

example page: https://tinyurl.com/y9uwnzvw

Edit: i checked ticket 22, but i already have those settings. Its confusing to jump to ticket 22, 23 and just guessing what needs to be changed

- i have the config included (which has the init.php and constants.php included). changed the settings to my server, but still get a blank page (see the apache log above)

I think the problem is you have the usage explained, but not how we can use this. just a simple test page would be nice to get us going. I found out in a ticket that you ask if we installed it through composer, why not put that in the readme?

update: i did some testing with some other CURL request and i got data without any problems (had to make sure outgoing port 8087 was open on my webserver firewall and also on my wowza server.

**Comment by IWriteThings** [comment] 2017-08-15 15:59
@nlmaca 

1. There is a current pull request waiting to update the documentation. I can't merge it because I don't work for Wowza and I am just a rando-dude helping them since I use the software too.

2. https://getcomposer.org/ - Composer is used to manage dependencies like the wowza rest library. You can read the getting started at https://getcomposer.org/doc/00-intro.md .

3. Here is some more documentation so you don't have to open the other ticket and follow along -

* Install Composer
* Make a directory then enter the directory
* make a composer.json file that includes the wowza stuff.

```
{
    "name": "phpixie/project",
    "type": "project",
    "description": "PHPixie skeleton project",
    "license": "BSD",
	"minimum-stability": "dev",
	"repositories": [
		{
			"type":"vcs",
			"url": "https://github.com/WowzaMediaSystems/wse-rest-library-php.git"
		}
	],
    "autoload": {
        "psr-4": {
            "": [
                "src/",
                "tests/"
            ],
            "Project\\App\\": [
                "bundles/app/src/"
            ]
        }
    },
    "require": {
		"wowza/wse-rest-library-php": "dev-master",
        "phpixie/default-bundle": "~3.2",
        "phpixie/bundle-framework": "~3.6",
        "phpixie/framework-bundle": "~3.3"
    },
    "require-dev": {
        "phpixie/test": "~3.0"
    },
    "extra": {
        "branch-alias": {
            "dev-master": "3.*-dev"
        }
    },
    "scripts": {
        "post-create-project-cmd": [
            "php ./console framework:generateBundle app",
            "php ./console framework:installWebAssets"
        ]
    }
}
```

* composer install
* create web folder then make index.php inside

```
<?php
//contents of index.php
require_once(__DIR__.'/../vendor/autoload.php');
require_once("../config.php");
```

* create a config.php in the root. notice the '../config.php' that means go up one directory.
* the config.php should look like

```
<?php

define( 'WOWZA_HOST','http://IPADDRESS:8087/v2' );
define( 'WOWZA_SERVER_INSTANCE', '_defaultServer_' );
define("WOWZA_VHOST_INSTANCE", "_defaultVHost_");
define("WOWZA_USERNAME", "username");
define("WOWZA_PASSWORD", "password");

$setup = new Com\Wowza\Entities\Application\Helpers\Settings();
$setup->setHost(WOWZA_HOST);
$setup->setUsername(WOWZA_USERNAME);
$setup->setPassword(WOWZA_PASSWORD);
$setup->setUseDigest(true);

$server = new Com\Wowza\Server($setup);
$sf = new Com\Wowza\Statistics($setup);
$response = $sf->getServerStatistics($server);
var_dump($response);
```

* go into the web folder again and type `php -S localhost:8123`
* Open browser and go to localhost:8123

You will now see the output from the server statistics. If you get errors. Trouble shoot them or come back here and post.

**Comment by nlmaca** [comment] 2017-08-15 16:21
Hi IwriteThings, im sorry. i totally overlooked you were not the owner of the repo ;). Thx for the answer though. I will look into it.

**Comment by IWriteThings** [comment] 2017-09-14 17:40
Have you resolved your issue? I would like to close this outstanding issue if it is resolved.

Thanks!

**Comment by nlmaca** [comment] 2017-09-14 18:01
You can close the ticket, i tried another method which worked for me. sorry i didn't update the issue.

**Comment by IWriteThings** [comment] 2017-09-18 15:34
Thanks a bunch. Closing the ticket.

**Closed as completed by IWriteThings** 2017-09-18 15:34 UTC
